export const MOCKED_GRAMMAR_THEORY_RESPONSE = JSON.stringify({
	category: "TENSES",
	topic: "PRESENT_PERFECT",
	rule_name: "Present Perfect Simple",
	level: "B2",
	summary:
		"The Present Perfect Simple connects the past with the present. It describes actions that happened at an indefinite time in the past or actions that started in the past and continue into the present.",
	theory:
		"<b>When do we use it?</b>\n\n•   To talk about <i>experiences or achievements</i> at an unspecified time in the past. The exact time is not important.\n    <i>Example: I have travelled to many countries. (When? Not specified.)</i>\n•   For actions that <i>started in the past and continue up to the present moment</i>. We often use <i>'for'</i> (duration) or <i>'since'</i> (starting point).\n    <i>Example: She has worked here since 2010.</i>\n•   For <i>recently completed actions</i> that have a present result. We often use adverbs like <i>'just', 'already', 'yet'</i>.\n    <i>Example: They have just released a new software update. (The update is now available.)</i>\n\n<b>Structure (Formula):</b>\n\nSubject + <b>have / has</b> + <b>Past Participle (V3)</b>\n\n•   <b>Positive:</b> I <code>have played</code>. He <code>has played</code>.\n•   <b>Negative:</b> I <code>have not (haven't) played</code>. He <code>has not (hasn't) played</code>.\n•   <b>Question:</b> <code>Have</code> you <code>played</code>? <code>Has</code> he <code>played</code>?\n\n<b>Examples:</b>\n\n•   <code>I have played Dota for five years.</code> (Started in the past, still playing.)\n•   <code>She has never written a line of code.</code> (An experience at an unspecified time.)\n•   <code>We haven't finished the project yet.</code> (Still ongoing, or just about to be finished.)\n•   <code>Has he ever visited Silicon Valley?</code> (Asking about a life experience.)\n•   <code>They have already deployed the new feature.</code> (Completed recently, with a current result.)\n\n<b>Typical Mistakes:</b>\n\n1.  <b>Using Past Simple instead of Present Perfect:</b>\n    •   Incorrect: <s>I lived here for 5 years (and still live here).</s>\n    •   Correct: <code>I have lived here for 5 years.</code>\n2.  <b>Incorrect auxiliary verb ('have'/'has'):</b>\n    •   Incorrect: <s>She have played.</s>\n    •   Correct: <code>She has played.</code>\n3.  <b>Using incorrect past participle (V3) form:</b>\n    •   Incorrect: <s>I have went to the meeting.</s>\n    •   Correct: <code>I have gone to the meeting.</code>\n4.  <b>Confusing 'for' and 'since':</b>\n    •   Incorrect: <s>I have worked here since 3 months.</s>\n    •   Correct: <code>I have worked here for 3 months.</code> (For a duration)\n    •   Correct: <code>I have worked here since March.</code> (Since a specific point in time)\n\n<b>In summary:</b> The Present Perfect Simple is used for actions connected to the present – either continuing, affecting the present, or being part of one's life experience up to now. Think of it as linking a past event to 'now'.",
});
